# Generated by Django 6.0 on 2026-06-19 14:06

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Paste the YouTube trailer link here.', max_length=500, null=True, validators=[movies.models.validate_youtube_url]),
        ),
    ]
