# Generated by Django 6.0 on 2026-07-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_event_eventbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(default='Chennai', max_length=100),
        ),
    ]
