# Generated by Django 6.0.6 on 2026-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_theater_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='screen_type',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4K DOLBY ATMOS', '4K Dolby Atmos'), ('LASER DTS X', 'Laser DTS X'), ('LASER ATMOS', 'Laser Atmos'), ('4K ATMOS', '4K Atmos'), ('DOLBY 7.1', 'Dolby 7.1')], default='2D', max_length=50),
        ),
    ]
